#这里存放的是TSGame基本配置文件
#配置文件版本(请勿修改)
version: 1.0
###数据库配置MYSQL###
#数据库IP
MysqlIp: '127.0.0.1'
#数据库名
MysqlRoot: 'TSGame'
#数据库用户名
MysqlUsername: 'TSGame'
#数据库密码
MysqlPassword: '123456789'
#数据库端口
MysqlPort: "3366"
#数据库表
MysqlTable: 'TSGame'
###挖矿疲劳设置###
#触发疲劳的矿石
DigBlock:
  - "minecraft:gold_ore"
  #金矿石
  - "minecraft:iron_ore"
  #铁矿石
  - "minecraft:coal_ore"
  #煤矿石
  - "minecraft:nether_gold_ore"
  #下届金矿石
  - "minecraft:lapis_ore"
  #青金石矿石
  - "minecraft:diamond_ore"
  #砖石矿石
  - "minecraft:redstone_ore[lit=false]"
  #红石矿石(不闪烁的时候)
  - "minecraft:redstone_ore[lit=true]"
  #红石矿石(闪烁的时候)
  - "minecraft:emerald_ore"
  #绿宝石矿石
  - "minecraft:nether_quartz_ore"
#下届石英矿石
#次触发疲劳时间(单位：秒)
DigTime: 60
#玩家最高挖掘活力
DigVigour: 2000
#玩家 10分钟 可以恢复的挖掘活力值
DigRecoveryVigour: 30
#进入疲劳时的语句
DigTired:
  - "好累啊！"
  - "今天状态不咋滴..."
###精神状态###
PlayerSpirit: 240
#玩家最高精神状态
PlayerRecoverySpirit: 48
#睡觉或者不在线一分钟恢复的精神状态值
PlayerSpiritMsg:
  #玩家没精神语句
  - "好困，太久没睡觉了..."
  - "再不睡觉，我感觉我会死的..."










#这里存放的是 LamLogin 的配置文件
#string: "配置String"
#int: 1654
#list:
# - "配置列表1"
# - "配置列表2"
